### ISSUE TITLE
JS errors when trying to upload file in FireFox

### ISSUE THREAD

**Issue by oleglark** [Kloudless/file-explorer#42] opened 2015-08-11 07:49 UTC
Environment: Win, Mac. FireFox 39.0.3

When the explorer is being invoked through explorer.choose(), the popup appears but number of errors appear:

ReferenceError: callback is not defined explorer.js:464:205438

Then selecting file to upload, file is added to the list. Pressing Upload starts upload, but once 100% is uploaded, new error is thrown:

TypeError: i.filesystem is not a function explorer.js:464:594370

And no Success event is invoked in the explorer itself. So, it is broken from that step.

**Comment by vinodc** [comment] 2015-08-11 07:59
Hi Oleg. I am unable to reproduce this in Firefox 39.0.3 on OS X using [this](http://jsfiddle.net/pseudonumos/PB565/embedded/result/) test JSFiddle. Could you let me know if you encounter the issue on that JSFiddle?

**Comment by oleglark** [comment] 2015-08-11 08:18
JSFiddle works ok for me. No errors. I have moved to JSFiddle same settings as we have in our implementation and it is working good as well. I`ll be trying to identify what exactly causes that issues and follow up on that in this thread

**Comment by oleglark** [comment] 2015-08-11 09:14
@vinodc it was not only issue related to FF, but to any browser. Specifically, when there is no info about any connected services - it will fail with this i.filesystem is not a function error. I have debugged it a bit and it seems like it failed to send some kind of postmessage. If you connect some services and then try to upload a file from computer - then it will work.
Fixed it by removing the account_key: true option from the explorer initialization. Without that option file upload works in all the cases (with and without connected serivces).

**Comment by vinodc** [comment] 2015-08-11 09:25
Thanks for the additional information Oleg. Would it be possible for you to share the configuration used that caused it to fail? I'd like to attempt to reproduce the error.

**Comment by oleglark** [comment] 2015-08-11 09:30
``` javascript
window.Kloudless.explorer({
	app_id: "APPID",
	direct_link: true,
	types: ['files'],
	account_key: true,
	computer: true,
	services: ['dropbox', 'box', 'gdrive', 'skydrive', 'copy', 'egnyte'],
	keys: ["KEY1", "KEY2"]
})
```

But i was not able to reproduce it in your JSFiddle, even with my options set, so, it is a bit weird

**Comment by oleglark** [comment] 2015-08-11 09:31
Also, clean out the local storage, so there will be no account info in it. This was one of the steps I needed to reproduce it.

**Comment by ahcai** [comment] 2015-08-12 23:18
@oleglark I wasn't able to reproduce the error on our test JSFiddle with your configuration even after cleaning out localStorage. Would you be able to link to any example page or JSFiddle that reproduces the error?

**Comment by vinodc** [comment] 2015-09-02 01:56
@oleglark Was this issue still a concern? Did you have an example page/JSFiddle we could reproduce the error on?

**Comment by oleglark** [comment] 2015-09-02 07:07
I`m not able to reproduce it anymore

**Comment by vinodc** [comment] 2015-09-02 09:57
Thanks for the quick response. I'll close this issue for now then.

**Closed by vinodc** 2015-09-02 09:57 UTC
Labels: bug
